version: '3.9'

services:

  node-pgdb:
    image: postgres:16.2-bullseye
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: e_shop_db
      POSTGRES_PASSWORD: qazwsx

    ports: 
      - "10000:5432"

    volumes:
      - "./data:/var/lib/postgresql/data"

